# Generated by Django 4.2.10 on 2024-04-06 02:10
import sys

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0002_strategyconfig_atr_coefficient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyconfig',
            name='ma',
            field=models.CharField(default='10', max_length=200, verbose_name='均线(多个周期「,」分割)'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='smoothing_period',
            field=models.CharField(default='9', max_length=200, verbose_name='平滑周期(多个周期「,」分割)'),
        )
    ]

    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
