# Generated by Django 4.2.10 on 2024-04-09 05:00
import sys

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0003_strategyconfig_ma_strategyconfig_smoothing_period_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategyconfig',
            name='ma',
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='fast_period',
            field=models.IntegerField(default='5', verbose_name='快线计算周期'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='long_period',
            field=models.IntegerField(default='60', verbose_name='趋势线计算周期'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='slow_period',
            field=models.IntegerField(default='20', verbose_name='慢线计算周期'),
        ),
        migrations.AlterField(
            model_name='strategyconfig',
            name='smoothing_period',
            field=models.IntegerField(default='9', verbose_name='平滑周期'),
        ),
    ]

    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
