# Generated by Django 4.2.10 on 2024-04-11 22:18
import sys

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0004_remove_strategyconfig_ma_strategyconfig_fast_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyconfig',
            name='factory',
            field=models.IntegerField(default='2', verbose_name='扩展系数'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='price_type',
            field=models.IntegerField(choices=[(1, '收盘价'), (2, '最高价'), (3, '最低价'), (4, '开盘价'), (5, '平均价'), (6, 'avg(high+low)'), (7, 'avg(high+low+close)'), (8, 'avg(open+high+low+close)')], default=1, verbose_name='Basic取值'),
        ),
    ]

    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []