# Generated by Django 4.2.10 on 2024-04-25 03:19
import sys

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0006_rename_okxklinedatasource_channels_datasourceconfig_channels_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradeconfig',
            old_name='okxtrader_api_key',
            new_name='api_key',
        ),
        migrations.RenameField(
            model_name='tradeconfig',
            old_name='okxtrader_api_secret_key',
            new_name='api_secret_key',
        ),
        migrations.RenameField(
            model_name='tradeconfig',
            old_name='backtesttrader_fee',
            new_name='fee',
        ),
        migrations.RenameField(
            model_name='tradeconfig',
            old_name='backtesttrader_fee_type',
            new_name='fee_type',
        ),
        migrations.RenameField(
            model_name='tradeconfig',
            old_name='backtesttrader_limit_order_execution_rate',
            new_name='limit_order_execution_rate',
        ),
        migrations.RenameField(
            model_name='tradeconfig',
            old_name='backtesttrader_min_fee',
            new_name='min_fee',
        ),
        migrations.RenameField(
            model_name='tradeconfig',
            old_name='okxtrader_passphrase',
            new_name='passphrase',
        ),
        migrations.RenameField(
            model_name='tradeconfig',
            old_name='backtesttrader_slippage',
            new_name='slippage',
        ),
        migrations.RenameField(
            model_name='tradeconfig',
            old_name='okxtrader_td_mode',
            new_name='td_mode',
        ),
        migrations.RenameField(
            model_name='tradeconfig',
            old_name='backtesttrader_volume_limit',
            new_name='volume_limit',
        ),
        migrations.RemoveField(
            model_name='tradeconfig',
            name='okxtrader_acct_domain',
        ),
        migrations.RemoveField(
            model_name='tradeconfig',
            name='okxtrader_domain',
        ),
        migrations.RemoveField(
            model_name='tradeconfig',
            name='okxtrader_flag',
        ),
        migrations.RemoveField(
            model_name='tradeconfig',
            name='okxtrader_inst_type',
        ),
        migrations.RemoveField(
            model_name='tradeconfig',
            name='okxtrader_leverage',
        ),
        migrations.RemoveField(
            model_name='tradeconfig',
            name='okxtrader_pub_domain',
        ),
        migrations.RemoveField(
            model_name='tradeconfig',
            name='okxtrader_ws_domain',
        ),
        migrations.AddField(
            model_name='datasourceconfig',
            name='work_flag',
            field=models.CharField(choices=[('1', '模拟盘'), ('0', '实盘'), ('2', '实盘(AWS)')], default='0', max_length=2, verbose_name='盘口'),
        ),
        migrations.AddField(
            model_name='tradeconfig',
            name='leverage',
            field=models.IntegerField(blank=True, default='3', verbose_name='杠杆倍数'),
        ),
        migrations.AddField(
            model_name='tradeconfig',
            name='work_flag',
            field=models.CharField(choices=[('1', '模拟盘'), ('0', '实盘'), ('2', '实盘(AWS)')], default='0', max_length=2, verbose_name='盘口'),
        ),
    ]

    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
