# Generated by Django 4.2.10 on 2024-04-25 06:35
import sys

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0007_rename_okxtrader_api_key_tradeconfig_api_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourceconfig',
            name='channels',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('1s', '秒K'), ('1m', '分钟K'), ('3m', '3分钟K'), ('5m', '5分钟K'), ('15m', '15分钟K'), ('30m', '30分钟K'), ('1H', '小时K'), ('4H', '4小时K'), ('1D', '日K')], default='', max_length=20, verbose_name='K线选择'),
        ),
        migrations.AlterField(
            model_name='datasourceconfig',
            name='symbols',
            field=models.TextField(blank=True, default='', verbose_name='InstId(多个逗号隔开)'),
        ),
    ]
    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
