# Generated by Django 4.2.10 on 2024-05-09 19:36
import sys

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0008_alter_datasourceconfig_channels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyconfig',
            name='add_position_rate',
            field=models.DecimalField(decimal_places=6, default=0.5, max_digits=36, verbose_name='加仓阈值'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='close_channel',
            field=models.IntegerField(default='10', verbose_name='唐奇安通道周期(平仓)'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='close_position_rate',
            field=models.DecimalField(decimal_places=6, default=2, max_digits=36, verbose_name='止损阈值'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='close_vhf_threshold',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=36, verbose_name='vhf平仓阈值(平仓)'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='expected_value',
            field=models.DecimalField(decimal_places=6, default=0.01, max_digits=36, verbose_name='期望账户净值波动'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='half_needle',
            field=models.BooleanField(default=True, verbose_name='唐奇安通道影线折半计算'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='open_channel',
            field=models.IntegerField(default='20', verbose_name='唐奇安通道周期(开仓)'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='open_vhf_threshold',
            field=models.DecimalField(decimal_places=6, default=0.5, max_digits=36, verbose_name='vhf开仓阈值(开仓)'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='take_profit_period',
            field=models.IntegerField(default='10', verbose_name='vmma计算周期(平仓)'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='true_range_window',
            field=models.IntegerField(default='20', verbose_name='波动率平滑周期'),
        ),
    ]
    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
