# Generated by Django 4.2.10 on 2024-05-11 08:29
import sys

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0009_strategyconfig_add_position_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyconfig',
            name='trade_type',
            field=models.IntegerField(choices=[(0, '顺势|反转'), (1, '顺势'), (2, '反转')], default=0, verbose_name='参与交易类型'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='win_loss_target',
            field=models.DecimalField(decimal_places=6, default=2.0, max_digits=36, verbose_name='反转交易预期盈亏比'),
        ),
    ]
    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []