# Generated by Django 4.2.10 on 2024-05-11 14:01
import sys

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0010_strategyconfig_trade_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyconfig',
            name='just_finish_k',
            field=models.BooleanField(default=True, verbose_name='仅使用已完成K线数据'),
        )
    ]
    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
