# Generated by Django 4.2.13 on 2024-06-12 03:14
import sys

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0011_strategyconfig_just_finish_k_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategyconfig',
            name='max_price',
            field=models.DecimalField(decimal_places=18, default='0', max_digits=36, verbose_name='网格上界'),
        ),
        migrations.AlterField(
            model_name='strategyconfig',
            name='min_price',
            field=models.DecimalField(decimal_places=18, default='0', max_digits=36, verbose_name='网格下界'),
        ),
    ]
    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
