# Generated by Django 4.2.13 on 2024-06-28 07:57
import sys

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0013_strategyconfig_over_buy_strategyconfig_over_sell_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuntimeConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('log_level', models.CharField(choices=[('CRITICAL', 'CRITICAL'), ('ERROR', 'ERROR'), ('WARNING', 'WARNING'), ('INFO', 'INFO'), ('DEBUG', 'DEBUG'), ('NOTSET', 'NOTSET')], default='INFO', max_length=20, verbose_name='日志等级')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '设置',
                'verbose_name_plural': '设置',
            },
        ),
    ]
    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
