# Generated by Django 4.2.13 on 2024-08-09 21:46
import sys

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0014_runtimeconfig_alter_datasourceconfig_channels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyconfig',
            name='limit_threshold',
            field=models.IntegerField(default=5, null=True, verbose_name='完全平仓阈值(连续平仓之后先清仓)'),
        ),
    ]
    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
