# Generated by Django 4.2.13 on 2024-09-03 12:17
import sys

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0015_strategyconfig_limit_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimeconfig',
            name='alert_token',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='通知token'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='alert_type',
            field=models.CharField(choices=[('console', '控制台输出'), ('dingding', '钉钉')], default='console', max_length=30, verbose_name='通知方式'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='data_dir',
            field=models.CharField(default='data', max_length=200, verbose_name='数据存储目录'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='download_dir',
            field=models.CharField(default='download', max_length=200, verbose_name='下载数据目录'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='emulation',
            field=models.BooleanField(default=False, verbose_name='回测数据仿真(开启后会使用小级别数据穿插在K线中)'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='emulation_interval',
            field=models.CharField(choices=[('1s', '秒K'), ('1m', '分钟K'), ('3m', '3分钟K'), ('5m', '5分钟K'), ('15m', '15分钟K'), ('30m', '30分钟K'), ('1H', '小时K'), ('4H', '4小时K'), ('6H', '6小时K'), ('8H', '8小时K'), ('12H', '12小时K'), ('1D', '日K')], default='5m', max_length=5, verbose_name='仿真填充K线'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='min_rate',
            field=models.DecimalField(decimal_places=4, default='0.005', max_digits=8, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='最小下单仓位'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='order_alert',
            field=models.BooleanField(default=False, verbose_name='开单提醒'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='proxy',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='网络代理(例: http://127.0.0.1:6789)'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='rolling_position',
            field=models.BooleanField(default=True, verbose_name='滚仓操作'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='target_interval',
            field=models.CharField(choices=[('1s', '秒K'), ('1m', '分钟K'), ('3m', '3分钟K'), ('5m', '5分钟K'), ('15m', '15分钟K'), ('30m', '30分钟K'), ('1H', '小时K'), ('4H', '4小时K'), ('6H', '6小时K'), ('8H', '8小时K'), ('12H', '12小时K'), ('1D', '日K')], default='30m', max_length=5, verbose_name='需仿真K线'),
        )
    ]

    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
