# Generated by Django 4.2.13 on 2024-09-05 10:31
import sys

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0016_runtimeconfig_alert_token_runtimeconfig_alert_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='runtimeconfig',
            name='allow_share_trading_account',
            field=models.BooleanField(default=False, verbose_name='允许策略间共享交易账户(开启后多个策略可使用同一个账户)'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='clear_run_data_on_error',
            field=models.BooleanField(default=True, verbose_name='运行异常时清空策略run_data'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='stop_on_error',
            field=models.BooleanField(default=False, verbose_name='运行异常时停止策略'),
        ),
        migrations.AddField(
            model_name='runtimeconfig',
            name='filter_release_strategy',
            field=models.BooleanField(default=False, verbose_name='只显示已发布策略(经过大量实盘的测试，PS： !=赚钱)'),
        ),
        migrations.AddField(
            model_name='tradeconfig',
            name='ccy',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='全仓默认保证金币种(不做全仓可不填)'),
        ),
        migrations.AddField(
            model_name='tradeconfig',
            name='order_type',
            field=models.CharField(choices=[('limit', '限价'), ('market', '市价')], default='market', max_length=20, verbose_name='默认下单类型'),
        ),
        migrations.AddField(
            model_name='tradeconfig',
            name='slippage_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(400)], verbose_name='现货/杠杆市价单滑点幅度(1-400档， 设置0直接下市价单)'),
        ),
        migrations.AddField(
            model_name='tradeconfig',
            name='trade_ins_type',
            field=models.IntegerField(choices=[(1, '现货'), (2, '杠杆'), (3, '合约'), (4, '期货'), (5, '期权')], default=3, verbose_name='默认交易产品类型'),
        ),

        migrations.AlterField(
            model_name='tradeconfig',
            name='td_mode',
            field=models.CharField(choices=[('isolated', '逐仓'), ('cross', '全仓'), ('cash', '非保证金'), ('spot_isolated', '现货带单')], default='isolated', max_length=20, verbose_name='默认交易模式'),
        )
    ]
    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
