# Generated by Django 4.2.13 on 2024-09-09 03:21
import sys

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0017_runtimeconfig_allow_share_trading_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasourceconfig',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='kline',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='profitlog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='runtimeconfig',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='strategyconfig',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='tradeconfig',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
    ]
    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = [o for o in operations if o.model_name in ("kline", "profitlog", "tradelog")]
        else:
            operations = [o for o in operations if o.model_name not in ("kline", "profitlog", "tradelog")]
