# Generated by Django 5.1.1 on 2024-10-15 08:15
import sys

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workstation", "0018_alter_datasourceconfig_channels_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategyconfig",
            name="close_change_rate",
            field=models.DecimalField(
                decimal_places=6,
                default="0.01",
                max_digits=8,
                verbose_name="平仓变化率限制",
            ),
        ),
        migrations.AddField(
            model_name="strategyconfig",
            name="close_position_when_direction_change",
            field=models.BooleanField(default=True, verbose_name="趋势反转时优先平仓"),
        ),
        migrations.AddField(
            model_name="strategyconfig",
            name="d_smoothing_factor",
            field=models.IntegerField(default="10", verbose_name="StochD平滑周期"),
        ),
        migrations.AddField(
            model_name="strategyconfig",
            name="k_num",
            field=models.IntegerField(default="10", verbose_name="MACD周期聚合"),
        ),
        migrations.AddField(
            model_name="strategyconfig",
            name="k_smoothing_factor",
            field=models.IntegerField(default="10", verbose_name="StochK平滑周期"),
        ),
        migrations.AddField(
            model_name="strategyconfig",
            name="min_histogram_num",
            field=models.IntegerField(default="10", verbose_name="最小MACD能量柱数"),
        ),
        migrations.AddField(
            model_name="strategyconfig",
            name="open_change_rate",
            field=models.DecimalField(
                decimal_places=6,
                default="0.01",
                max_digits=8,
                verbose_name="加仓变化率限制",
            ),
        ),
        migrations.AddField(
            model_name="strategyconfig",
            name="peak_over_buy",
            field=models.IntegerField(
                default="90",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="极限超买阈值",
            ),
        ),
        migrations.AddField(
            model_name="strategyconfig",
            name="peak_over_sell",
            field=models.IntegerField(
                default="10",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="极限超卖阈值",
            ),
        ),
        migrations.AddField(
            model_name="strategyconfig",
            name="period",
            field=models.IntegerField(default="10", verbose_name="RSI平滑周期"),
        ),
        migrations.AddField(
            model_name="strategyconfig",
            name="position_num",
            field=models.IntegerField(default="2", verbose_name="分仓"),
        ),
    ]
    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
