# Generated by Django 5.1.1 on 2025-03-11 10:55
import sys

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0019_strategyconfig_close_change_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyconfig',
            name='bias_risk_rate',
            field=models.DecimalField(decimal_places=6, default='0.2', max_digits=36, verbose_name='乖离率反转比例'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='force_risk_rate',
            field=models.DecimalField(decimal_places=6, default='0.2', max_digits=36, verbose_name='强制风控系数'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='position_split',
            field=models.CharField(default='1,2,3', max_length=500, verbose_name='仓位划分'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='start_condition',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='开始条件'),
        ),
        migrations.AddField(
            model_name='strategyconfig',
            name='stop_condition',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='停止条件'),
        )
    ]

    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []
