# Generated by Django 5.1.1 on 2025-03-19 06:53
import sys

import django.core.validators
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workstation', '0020_strategyconfig_bias_risk_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategyconfig',
            name='k_merge_period',
            field=models.IntegerField(default='0', verbose_name='K线合并数量'),
        )
    ]
    if "migrate" in sys.argv:
        db = [arg.split("=")[1] for arg in sys.argv if arg.startswith("--database")]
        if len(db) > 0 and db[0] == "data":
            operations = []

